### ISSUE TITLE
[QUESTION]: Could we consider changing Navigation method to support iOS 15?

### ISSUE THREAD

**Issue by haIIux** [0xOpenBytes/ios-base#10]
### Description

It was brought up in the community Discord that we target iOS 16 with this project. A few project questions listed below for community discussion.

1. Would it be something that we could easily backport to iOS 15 to open up the ability for others to utilize this base template? 
2. Could we utilize something similar to the recent `./rename.sh` script to change the iOS target and generate the appropriate changes?

**Comment by 0xLeif** [comment]
I don't think there is an easy way to support both iOS 16 and 15 while using NavigationStack and NavigationPath.. If we support 15 we would have to separate the navigation into two different implementations. One could use this project to create a new project that supports iOS 15. We might think about having someone use this template for the iOS 15 support if needed.

**Comment by haIIux** [comment]
With how quickly it seems there is a new iOS (every 10-12 months) and how [Mixpanel adoption rate](https://mixpanel.com/trends/#report/ios_16/from_date:-102,report_unit:week,to_date:0) shows, is it worth the effort as the current adoption rate of iOS 16 is over 75%?

**Comment by devahmedshendy** [comment]
I cannot guarantee I would use this template as it is, but willing to learn from it, I will get back here with request to open the discussion again if I found it is worth.

But for me, if there is a good pattern for navigation prior iOS 16, definitely worth to implement.

**Comment by 0xLeif** [comment]
Closing this ticket sine we have decided to keep the minimum deployment target of iOS 16.
