### ISSUE TITLE
[FEATURE]: Add Renaming Safety to ./rename.sh

### ISSUE THREAD

**Issue by haIIux** [0xOpenBytes/ios-base#18]
### Description

During a recent PR review, I attempted to rename a project to `swiftlint-pr`. This worked well and renamed everything, including `@main` project struct (shown below) in which threw a complier error and did not allow the project to build. While it is safe to assume that your average user with the help of the compiler warnings *should* be able to understand how to fix this, it is in my opinion that we may want to explore options to build in some sort of safety which does one of the follow...

1. Alerts the user upon attempting to enter a name that contains a character which would throw the error and allows them to either enter Y or N to continue with the understanding, which in turn will complete the rename as they acknowledge it or provide them the ability to select a new name upon entering N.
2. Not allow the renaming and force them to rename without the use of the character.

In my preference, we should opt for option 1 as it allows freedom to the user to make their own decision as the `./rename.sh` script changes more then just the in-compiler naming.

**Comment by 0xLeif** [comment]
We should go with option 2. 

The project name should only include the following characters:
- alphanumerics
- "_" 

The project name should not start with a number.

**Comment by haIIux** [comment]
Option 2 it is!
